config/routes.rb
TProject::Application.routes.draw do
  resources :tasks, :only => [:edit, :create, :update, :destroy]
  resources :projects, :except => :show 
  resources :users, :only => [:new, :create, :destroy]
  resources :sessions, :only => [:new, :create]

   root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :user
  has_many :tasks , :dependent => :destroy
  
  accepts_nested_attributes_for  :tasks, :allow_destroy => true 
  attr_accessible :tasks_attributes  
  attr_accessible :name
  
  validates :name, :presence   => true,
                   :length     => { :maximum => 150}

end

app/models/task.rb
class Task < ActiveRecord::Base
  
  belongs_to :project
  
  validates :name, :presence   => true
  
  attr_accessible :name, :time_end, :project_id, :prioritise, :is_done

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :projects, :dependent => :destroy
  
  attr_accessible :name, :password, :password_confirmation
  attr_accessor   :password
  
  before_save :encrypt_password
  
  validates :name, :presence   => true,
                   :length     => { :within => 2..40},
                   :uniqueness => true
  validates :password, :presence     => true,
                       :confirmation => true,
		       :length       => { :within => 6..40}
 
  def self.authenticate(name, password)
     user = find_by_name(name)
     if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
       user
     else
       nil
     end
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.password_salt == cookie_salt) ? user : nil
  end

  
  private
  
    def encrypt_password
       if password.present?
         self.password_salt = BCrypt::Engine.generate_salt
         self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
       end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  before_filter :authenticate

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.find_all_by_user_id(current_user.id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.js { @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    
    respond_to do |format|
      format.html #edit.html.erb
      format.js {@project}
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path }
        format.js { @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to root_path }
        format.js {@project} #update.js.erb 
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project_id = params[:id]
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.js { @project_id }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_filter :authenticate, :only => [:new, :create]  

  def new
  end
  
  def create
     user = User.authenticate(params[:name], 
                              params[:password])
     if user
       sign_in user
       redirect_to root_path
     else
       flash.now[:error] = "Invalid name/password combination."
       render 'new'
     end
   end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html #edit.html.erb
      format.js {@task}
    end

  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path }
        format.js { @task }
      else
        format.html { redirect_to root_path }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to root_path }
        format.js {@task}
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task_id = params[:id]
    @task.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { @task_id }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate, :only => [:new, :create]  

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Test Application!"
      redirect_to root_path
    else
      @user.password = ''
      @user.password_confirmation = ''
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:remember_token] = [user.id, user.password_salt]
    self.current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
#  def current_user?(user)
#    user == current_user
#  end

  def authenticate
     deny_access unless signed_in?
  end
  
  def deny_access
#    store_location
    redirect_to new_session_path, :notice => "Please sign in to access this page."
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      session[:remember_token] || [nil, nil]
    end
    
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TProject</title>
  <%= stylesheet_link_tag "custom", :media => "screen" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>

        <%= yield %>
    </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project_form.html.erb
<div id=project_form>
<%= form_for(@project, :remote=>true) do |f| %>
    <%= f.text_field :name, :size=>"85px" %>
    <%= f.submit f.object.new_record? ? 'Create' : 'Update'%>
<% end %>  
</div>

app/views/projects/_project_table.html.erb
<table class="project_tasks" id=table_project_<%=@project.id%>>

  <tr class="project_object">
    <td class='check_box'>
      <%=image_tag("img02.jpeg", :class => "img_project")%>
    </td>
    <td class="nbsp">&nbsp</td>
    <td class=project_name>
      <div id=project_show_<%=@project.id%> >
      <%=@project.name%>
      </div>
    </td>
    <td class="action">
      <%= link_to (image_tag("button2.jpeg", :alt =>  "Edit", :class =>"buttom_edit_project")).html_safe, edit_project_path(@project), :remote => true %> | 
      <%= link_to (image_tag("button3.jpeg", :alt =>  "Destroy", :class =>"buttom_destroy_project")).html_safe, @project, confirm: 'Are you sure?', method: :delete, :remote => true %>
    </td>
  </tr>

<div id=index_project_tasks>
  <tr class='new_task_form'>
    <td class='check_box'>
      <%=image_tag("img03.jpeg", :class => "img_new_task")%></td>
    <td class="nbsp"></td>
    <td colspan='2'>
      <div id=new_task_form_project_<%=@project.id%>>
      <%@task = @project.tasks.build(:project_id => @project.id)%>
      <%= render 'tasks/task_form'%>
      </div>
    </td>
  </tr>

   <% @project.tasks.each do |task| unless task.id==nil%>
   <% @task = task%>
     <%= render 'tasks/task_tr'%>
   <% end %> 
</div>
   <% end %> 
</table>

app/views/projects/create.js.erb
$("#project_form").remove()
$("#index_project").append("<%= escape_javascript(render('project_table')) %>")

app/views/projects/destroy.js.erb
$("#table_project_<%= @project_id %>").toggle('slide')

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/edit.js.erb
$("#project_show_<%= @project.id %>").html("<%= escape_javascript(render('project_form')) %>")

app/views/projects/index.html.erb
<h1>Listing projects</h1>
<h2>From <%= current_user.name%></h2>
<br/>
<div id=index_project>
<% @projects.each do |project| %>
<% @project = project%>
<%= render 'project_table'%>
<br/>
<% end %>
</div>
<%= link_to (image_tag("button1.jpeg", :alt =>  "Add Project", :id =>"buttom_add_project")).html_safe, new_project_path, :remote => true %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$("#index_project").append("<%= escape_javascript(render('project_form')) %>")

app/views/projects/update.js.erb
$("#project_show_<%= @project.id %>").html("<%= escape_javascript(@project.name) %>")

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :is_done %><br />
    <%= f.check_box :is_done %>
  </div>
  <div class="field">
    <%= f.label :time_end %><br />
    <%= f.datetime_select :time_end %>
  </div>
  <div class="field">
    <%= f.label :prioritise %><br />
    <%= f.number_field :prioritise %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task_for_index.html.erb
            <% unless @task.time_end ==nil%>
              Done: <%= @task.time_end%> | 
            <% end %>
            <%= @task.name %>

app/views/tasks/_task_form.html.erb
<%= form_for(@task, :remote=>true)  do |f| %>
    <%= f.hidden_field :project_id%>
    <%= f.text_field :name, :class=> "text_field", 
                     :value => f.object.new_record? ? 'Start typing here to create a task...' : @task.name,
                     :onfocus=>"if (this.value == 'Start typing here to create a task...') {this.value=''; this.style.color='#000';}"%>
    <%= f.submit f.object.new_record? ? 'Add Task' : 'Update', :class=>"button"%>
<% end %>  

app/views/tasks/_task_tr.html.erb
      <tr id=tr_task_<%=@task.id%> class='task'>
        <td class='check_box'>
          <%= form_for @task, :remote => true do |f| %>
          <%= f.check_box :is_done %>
          <% end %>
        </td>
        <td class="nbsp"></td>
        <td class='task_name'> 
          <div id=task_show_<%=@task.id%> class=task_name_show>
            <%= render 'tasks/task_for_index'%>
          </div>
        </td>
        <td class="action">
          <%=  link_to (image_tag("button4_.png", :alt =>  "Edit", :class =>"buttom_edit_task")).html_safe, edit_task_path(@task), :remote => true%> |
          <%= link_to (image_tag("button5_.png", :alt =>  "Destroy", :class =>"buttom_destroy_task")).html_safe, @task, confirm: 'Are you sure?', method: :delete, :remote => true %>
        </td>
      </tr>

app/views/tasks/create.js.erb
$("#table_project_<%=@task.project_id%>").append("<%= escape_javascript(render('task_tr')) %>")
$(".new_task")[0].reset()

app/views/tasks/destroy.js.erb
$("#tr_task_<%= @task_id %>").toggle('slide')

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$("#task_show_<%= @task.id %>").html("<%= escape_javascript(render('task_form')) %>")

app/views/tasks/update.js.erb
$("#task_show_<%= @task.id %>").html("<%= escape_javascript(render('task_for_index')) %>")

app/views/users/new.html.erb
<h1>New user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>